<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd">
<suite parallel="tests" name="Failed suite [Suite]" guice-stage="DEVELOPMENT">
  <test thread-count="5" parallel="tests" name="Error Validation Test(failed)">
    <classes>
      <class name="subratpattanaik.tests.ErrorValidations">
        <methods>
          <include name="launchApplication"/>
          <include name="submitOrder"/>
          <include name="tearDown"/>
        </methods>
      </class> <!-- subratpattanaik.tests.ErrorValidations -->
    </classes>
  </test> <!-- Error Validation Test(failed) -->
  <test thread-count="5" parallel="tests" name="Submit Order Test(failed)">
    <classes>
      <class name="subratpattanaik.tests.SubmitOrderTest">
        <methods>
          <include name="orderHistoryTest"/>
          <include name="submitOrder" invocation-numbers="1"/>
          <include name="launchApplication"/>
          <include name="tearDown"/>
        </methods>
      </class> <!-- subratpattanaik.tests.SubmitOrderTest -->
    </classes>
  </test> <!-- Submit Order Test(failed) -->
</suite> <!-- Failed suite [Suite] -->
